"use client";

import Link from "next/link";
import { useState } from "react";
import { useCart } from "@/components/cart/cart-provider";
import { Icon } from "@/components/ui/icons";

const links = [{ href: "/", label: "Home" }, { href: "/shop", label: "Shop" }, { href: "/shop?edit=new", label: "New Arrivals" }, { href: "/shop?collection=essential", label: "Collections" }, { href: "/shop?edit=best", label: "Best Sellers" }, { href: "/about", label: "About" }, { href: "/contact", label: "Contact" }];

export function Navbar() {
  const [menuOpen, setMenuOpen] = useState(false); const { itemCount, setOpen } = useCart();
  return <><div className="bg-looms-teal px-3 py-2 text-center text-[9px] font-medium leading-4 tracking-[0.09em] text-looms-cream sm:text-[10px] sm:tracking-[0.14em]">COMPLIMENTARY SHIPPING ON ORDERS OVER IDR 500.000</div><header className="border-b border-looms-teal/15 bg-looms-cream"><nav className="mx-auto flex h-16 max-w-[1440px] items-center justify-between px-3 sm:px-5 lg:h-20 lg:px-10" aria-label="Primary navigation"><div className="flex min-w-0 flex-1 items-center gap-1 lg:hidden"><button aria-label="Open navigation" onClick={() => setMenuOpen(true)} className="grid h-11 w-11 place-items-center"><Icon name="menu" className="h-5 w-5" /></button><Link href="/shop#catalog-search" aria-label="Search products" className="grid h-11 w-11 place-items-center"><Icon name="search" className="h-5 w-5" /></Link></div><Link href="/" className="shrink-0 font-display text-[1.65rem] tracking-[0.12em] text-looms-teal sm:text-3xl sm:tracking-[0.18em] lg:text-4xl">LOOMS</Link><div className="hidden flex-1 justify-center gap-6 lg:flex">{links.map((link) => <Link key={link.label} href={link.href} className="text-xs tracking-[0.08em] text-looms-teal hover:text-looms-gray">{link.label}</Link>)}</div><div className="flex min-w-0 flex-1 items-center justify-end gap-1"><Link href="/shop#catalog-search" aria-label="Search products" className="hidden lg:grid lg:h-11 lg:w-11 lg:place-items-center"><Icon name="search" className="h-5 w-5" /></Link><button aria-label="Wishlist" className="hidden lg:grid lg:h-11 lg:w-11 lg:place-items-center"><Icon name="heart" className="h-5 w-5" /></button><button onClick={() => setOpen(true)} aria-label={`Open cart, ${itemCount} items`} className="relative grid h-11 w-11 place-items-center"><Icon name="bag" className="h-5 w-5" />{itemCount > 0 && <span className="absolute right-0 top-0 grid h-4 w-4 place-items-center rounded-full bg-looms-teal text-[9px] text-looms-cream">{itemCount}</span>}</button></div></nav></header>{menuOpen && <div className="fixed inset-0 z-[60]"><button aria-label="Close navigation" onClick={() => setMenuOpen(false)} className="absolute inset-0 bg-looms-teal/35" /><div role="dialog" aria-modal="true" aria-label="Mobile navigation" className="relative flex h-full w-[88%] max-w-sm flex-col bg-looms-cream px-6 pb-[max(1.5rem,env(safe-area-inset-bottom))] pt-[max(1.5rem,env(safe-area-inset-top))]"><div className="flex items-center justify-between"><span className="font-display text-2xl tracking-[0.14em]">LOOMS</span><button aria-label="Close navigation" onClick={() => setMenuOpen(false)} className="grid h-11 w-11 place-items-center"><Icon name="close" className="h-5 w-5" /></button></div><div className="mt-10 flex flex-col">{links.map((link) => <Link key={link.label} href={link.href} onClick={() => setMenuOpen(false)} className="border-b border-looms-teal/15 py-4 text-sm tracking-[0.08em]">{link.label}</Link>)}</div></div></div>}</>;
}
