"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";

const statuses = ["PENDING", "CONFIRMED", "PROCESSING", "PACKED", "SHIPPED", "COMPLETED", "CANCELLED"];
const money = (value: number | string) => `Rp ${Number(value).toLocaleString("id-ID")}`;
type Detail = { order: { id: string; order_number: string; status: string; subtotal: number | string; shipping_amount: number | string; total: number | string; customer_notes: string | null }; customer: { full_name: string; whatsapp_number: string; email: string | null }; address: { province: string; city: string; district: string; postal_code: string; full_address: string }; items: Array<{ id: string; product_name_snapshot: string; variant_name_snapshot: string | null; quantity: number; unit_price: number | string }>; history: Array<{ id: string; from_status: string | null; to_status: string; created_at: string }> };

export default function AdminOrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`/api/admin/orders/${id}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || "Failed to load order"); setDetail(data); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Failed to load order")); }, [id]);
  async function updateStatus(status: string) { if (!detail) return; setSaving(true); setError(null); try { const response = await fetch(`/api/admin/orders/${id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || "Failed to update status"); setDetail({ ...detail, order: { ...detail.order, status }, history: [...detail.history, { id: crypto.randomUUID(), from_status: detail.order.status, to_status: status, created_at: new Date().toISOString() }] }); } catch (updateError) { setError(updateError instanceof Error ? updateError.message : "Failed to update status"); } finally { setSaving(false); } }
  if (error) return <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>;
  if (!detail) return <p className="text-sm text-gray-500">Memuat pesanan...</p>;
  return <div className="mx-auto max-w-4xl space-y-6"><Link href="/admin/orders" className="text-sm text-looms-teal hover:underline">← Semua pesanan</Link><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[0.16em] text-gray-500">Order</p><h1 className="mt-2 font-display text-4xl text-looms-teal">{detail.order.order_number}</h1></div><select disabled={saving} value={detail.order.status} onChange={(event) => void updateStatus(event.target.value)} className="rounded-lg border border-gray-300 px-3 py-2.5 text-sm">{statuses.map((status) => <option key={status}>{status}</option>)}</select></div><div className="grid gap-6 md:grid-cols-2"><section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-display text-2xl text-looms-teal">Customer</h2><p className="mt-4 text-sm">{detail.customer.full_name}<br />{detail.customer.whatsapp_number}<br />{detail.customer.email ?? "-"}</p></section><section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-display text-2xl text-looms-teal">Pengiriman</h2><p className="mt-4 text-sm">{detail.address.full_address}<br />{detail.address.district}, {detail.address.city}<br />{detail.address.province}, {detail.address.postal_code}</p></section></div><section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-display text-2xl text-looms-teal">Items</h2><div className="mt-4 divide-y divide-gray-200">{detail.items.map((item) => <div key={item.id} className="flex justify-between gap-4 py-3 text-sm"><span>{item.product_name_snapshot}<br /><small className="text-gray-500">{item.variant_name_snapshot ?? "-"} · Qty {item.quantity}</small></span><span>{money(Number(item.unit_price) * item.quantity)}</span></div>)}</div><div className="mt-4 border-t border-gray-200 pt-4 text-sm"><p className="flex justify-between">Subtotal <span>{money(detail.order.subtotal)}</span></p><p className="mt-2 flex justify-between">Shipping <span>{money(detail.order.shipping_amount)}</span></p><p className="mt-3 flex justify-between text-base font-medium">Total <span>{money(detail.order.total)}</span></p></div>{detail.order.customer_notes && <p className="mt-5 border-t border-gray-200 pt-4 text-sm">Catatan: {detail.order.customer_notes}</p>}</section><section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-display text-2xl text-looms-teal">Status history</h2><div className="mt-4 space-y-3 text-sm">{detail.history.map((entry) => <p key={entry.id}>{entry.from_status ?? "NEW"} → {entry.to_status} <span className="text-gray-500">{new Date(entry.created_at).toLocaleString("id-ID")}</span></p>)}</div></section></div>;
}
